import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../Components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <>
        <div className="relative w-full flex items-center justify-center ">
          <Navbar />
        </div>
        {children}
      </>
    </html>
  );
}
